### ISSUE TITLE
Can't call method "isa" without a package or object reference at /usr/local/share/perl5/Net/XMPP/Protocol.pm line 2471

### ISSUE THREAD

**Issue by webudo** [toddr/perl-net-jabber-bot#4]
Hello,
I'm trying to run bot_example.pl but I get this error:

2012/12/11 10:08:15 DEBUG (416): Sending presence to tell world that we are logged in
Can't call method "isa" without a package or object reference at /usr/local/share/perl5/Net/XMPP/Protocol.pm line 2471

Please help!

Thanks

**Comment by toddr** [comment]
I'm closing this as it sounds to be a Net::XMPP issue.
